
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-70-127.eu-west-1.compute.amazonaws.com:5432/db4m9j1aiciqu9
    username: mpguhyvuaperow
    password: 5e09bc386116856624bc9a77d8c8292737926cc26752b1f2ce6bf73178d4caae

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp.use_jdbc_metadata_defaults: false